# Generated by Django 5.2.1 on 2025-06-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт пользователем из истории'),
        ),
    ]
