# Generated by Django 5.2.1 on 2025-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_image_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Базовое имя изображений (например, 1_1)'),
        ),
    ]
